### ISSUE TITLE
Any readme files?

### ISSUE THREAD

**Issue by petronny** [zaycakitayca/fvwm-menu-gnome#1]
Hi,
  I found this package in AUR. But I have no idea about how to use it.
  Could you add a readme or some examples for it?
Thanks.

**Comment by lesf0** [comment]
Hello,
This script was developed as a replacement for FVWM standart bash-script called fvwm-menu-desktop. You can find examples for original fvwm script and replace "fvwm-menu-desktop args" with "fvwm-menu-gnome" command.
Also i've uploaded my working config as example, you can use it.
P.S. FVWM is a x11 window manager, and this script requies it to be installed

**Comment by petronny** [comment]
It works pretty well!
But it is a pity that there are no icons for the entries.
Should it be the next improvement?

**Comment by lesf0** [comment]
Thanks for comment
I'll work on it soon
